### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by kingling** [b1b2b3b4b5b6/dllink_assist#1]
感谢！
我玩的国服，也试了一下，注释掉assert(NONE)后运行ok，服务器不一样界面还是有点差异的，会找不到可转移目标，尝试截了main_pvp和main_work替换，work界面还是可以点击进入卡组编辑器，会在此处死循环。目前这个直接用，打npc也就在决斗结束时候会报个错，是否重新截取img替换即可？另外国际服的work那个图块点击后不会进入卡组编辑器？（就像store那样）想要在国服用这个，有什么好办法吗？

**Comment by b1b2b3b4b5b6** [comment]
国际最右边的界面进去是决斗工作室, 没试过国服, 按理说替换ui资源就可以了

**Comment by chenmg2020** [comment]
> 感谢！
> 我玩的国服，也试了一下，注释掉assert(NONE)后运行ok，服务器不一样界面还是有点差异的，会找不到可转移目标，尝试截了main_pvp和main_work替换，work界面还是可以点击进入卡组编辑器，会在此处死循环。目前这个直接用，打npc也就在决斗结束时候会报个错，是否重新截取img替换即可？另外国际服的work那个图块点击后不会进入卡组编辑器？（就像store那样）想要在国服用这个，有什么好办法吗？

请问下大佬，为啥要注释掉assert(NONE)呢？我注释掉依然无法启动，请问你是在哪个界面启动程序的呢？雷电模拟器的主页吗？还是游戏的主页？
